### ISSUE TITLE
Cannot access to my account

### ISSUE THREAD

**Issue by Bigdaifr** [zaosoula/ha-voltalis#2]
Hi,
I try to use the add on but I cannot access to it.
Whenever I try to connect, the log returns an issue with the credentials.
I use the correct credentials but it always return the error.

The log info:
[09:59:50] INFO: Starting bridge service.
yarn run v1.22.22
warning package.json: No license field
$ node dist/index.js
(node:121) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/dist/lib/voltalis.js:141
                            throw new Error('Bad Credentials');
                                  ^
Error: Bad Credentials
    at Voltalis.<anonymous> (/dist/lib/voltalis.js:141:35)
    at Generator.throw (<anonymous>)
    at rejected (/dist/lib/voltalis.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Node.js v22.11.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by zaosoula** [comment]
It's fixed
